posts/api/urls.py
from django.conf.urls import url

#API views
from posts.api.views import (PostListAPIView,
                             PostDetailAPIView,
                             PostDeleteAPIView,
                             PostUpdateAPIView,
                             PostCreateAPIView,
                             PostLikeAPIToggleView,
                             PostDraftListAPIView,
                             PostPublishedListAPIView)

urlpatterns = [
    # API post URLs
    url(r'^$', PostListAPIView.as_view(), name='list_api'),
    url(r'^published/$', PostPublishedListAPIView.as_view(), name='list_published_api'),
    url(r'^draft/$', PostDraftListAPIView.as_view(), name='list_draft_api'),
    url(r'^create/$', PostCreateAPIView.as_view(), name='create_api'),
    url(r'^(?P<pk>\d+)/$', PostDetailAPIView.as_view(), name='detail_api'),
    url(r'^(?P<pk>\d+)/update/$', PostUpdateAPIView.as_view(), name='update_api'),
    url(r'^(?P<pk>\d+)/delete/$', PostDeleteAPIView.as_view(), name='delete_api'),
    # API post like URL
    url(r'^(?P<pk>\d+)/like/$', PostLikeAPIToggleView.as_view(), name='post_api_like'),

]

posts/urls.py
from django.conf.urls import url, include

# Import views-post
from posts.views import (post_create,
                         post_detail,
                         post_list,
                         post_update,
                         post_delete,
                         PostLikeRedirectView)

urlpatterns = [
    # Web post URLs
    url(r'^$', post_list, name='url_post_list'),
    url(r'^create/$', post_create, name='url_post_create'),
    url(r'^(?P<pk>\d+)/$', post_detail, name='url_post_detail'),
    url(r'^(?P<pk>\d+)/update/$', post_update, name='url_post_update'),
    url(r'^(?P<pk>\d+)/delete/$', post_delete, name='url_post_delete'),
    # Tags post-blog
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', post_list, name='url_post_list_by_tag'),
    # Like post-blog
    url(r'^(?P<pk>\d+)/like/$', PostLikeRedirectView.as_view(), name='post_like'),

    # API post URLs
    #url(r'^api/posts/', include('posts.api.urls', namespace='posts-api')),
]

wambo/urls.py
# -*- coding:utf-8 -*-
"""wambo URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin

from users import urls as users_urls
from posts import urls as posts_urls
from adminweb import urls as adminweb_urls
from comments import urls as comments_url

from django.contrib.sitemaps.views import sitemap
from posts.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^adminweb/', include(adminweb_urls, namespace='adminweb')),

    # Import Posts URLs
    url(r'^', include(posts_urls, namespace='post')),
    # Import Comments URLs
    url(r'^comments/', include(comments_url, namespace='comments')),
    # API comments URLs
    url(r'^api/comments/', include('comments.api.urls', namespace='comments-api')),
    # Import User URLs
    url(r'', include(users_urls)),
    # API post URLs
    url(r'^api/posts/', include('posts.api.urls', namespace='posts-api')),
    # sitemap
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/api/views.py
from rest_framework.generics import (
    CreateAPIView,
    ListAPIView,
    RetrieveAPIView,
    UpdateAPIView,
    DestroyAPIView,
    RetrieveUpdateAPIView
)
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions
from django.shortcuts import get_object_or_404


# Filters
from rest_framework.filters import (
    SearchFilter,
    OrderingFilter)

# Pagination
from rest_framework.pagination import (
    LimitOffsetPagination,
    PageNumberPagination)
from .pagination import PostLimitOffsetPagination, PostPageNumberPagination

# Permissions
from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly)
from .permissions import IsOwnerOrReadOnly

# Models
from posts.models import Post
from .serializers import PostListSerializer, PostDetailSerializer, PostCreateSerializer


class PostCreateAPIView(CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateSerializer

    def perform_create(self, serializer):
        """
        Gestiana la creación del articulo vinculado al usuario actual.
        :param serializer: objeto serializer de la del Modelos
        :return: Obejto de respuesta json son los datos
        """
        serializer.save(user=self.request.user)


class PostDetailAPIView(RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    permission_classes = [AllowAny]


class PostUpdateAPIView(RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateSerializer
    permission_classes = [IsOwnerOrReadOnly]

    def perform_update(self, serializer):
        serializer.save(user=self.request.user)


class PostDeleteAPIView(DestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    permission_classes = [IsOwnerOrReadOnly]


class PostListAPIView(ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostListSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['title', 'content', 'user__first_name']
    pagination_class = PostPageNumberPagination # PostLimitOffsetPagination
    permission_classes = [AllowAny]


class PostPublishedListAPIView(ListAPIView):
    """
    View to list all user published post.

    * Allow any users are able to access this view.
    """
    serializer_class = PostListSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['title', 'content', 'user__first_name', 'timestamp']
    pagination_class = PostPageNumberPagination  # PostLimitOffsetPagination
    permission_classes = [AllowAny]

    def get_queryset(self):
        data = self.request
        queryset_list = Post.objects.userpostlist(request=data)
        return queryset_list


class PostDraftListAPIView(ListAPIView):
    """
    View to list all user draft post.

    * Only owner users are able to access this view.
    """
    serializer_class = PostListSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['title', 'content', 'user__first_name', 'timestamp']
    pagination_class = PostPageNumberPagination  # PostLimitOffsetPagination
    permission_classes = [IsOwnerOrReadOnly]

    def get_queryset(self):
        data = self.request
        queryset_list = Post.objects.userdraftlist(request=data)
        return queryset_list


class PostLikeAPIToggleView(APIView):
    """
    View to list all users in the system.

    * Requires token authentication.
    * Only admin users are able to access this view.
    """
    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, format=None, pk=None):
        """
        """
        obj = get_object_or_404(Post, pk=pk)
        url_ = obj.get_absolute_url()
        user = self.request.user

        updated = False
        liked = False
        if user.is_authenticated():
            if user in obj.likes.all():
                liked = False
                obj.likes.remove(user)
            else:
                liked = True
                obj.likes.add(user)
            updated = True
        data = {
            'updated': updated,
            'like': liked
        }
        return Response(data)

posts/views.py
# -*- coding:utf-8 -*-
from urllib.parse import quote_plus

from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
from taggit.models import Tag

# Create your views here.
from posts.form import PostForm
from posts.models import Post
from comments.forms import CommentForm
from comments.models import Comment

# Views Django
from django.views.generic import RedirectView

from django.db.models import Count


def post_home(request):
    return HttpResponse("<h1>Hola</h1>")


@login_required
def post_create(request):
    """
    Gestiona la creación de un aritculo del blog
    :param request: Objeto Htttprequest con los parametros de la petición
    :return: objeto Httpresponse con los parametros de respuesta
    """

    if not request.user.is_authenticated():
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        # Without this next line the tags won't be saved.
        form.save_m2m()
        # message success
        messages.success(request, 'Post Successfully Created')
        return redirect('post:url_post_detail', pk=instance.pk)
    # else:
    #     messages.error(request, 'Post  NOT Successfully Created')
    context = {
        'form': form,
        'title': 'Post Form',
    }
    return render(request, 'posts/post_form.html', context)


def post_detail(request, pk):
    """
    Gestiona los detalles de los articulos del post
    :param request: objeto HttpRequiest con los datos de la petición
    :param pk: parametro identificador del articulo publicado
    :return: objeto HttpResponse con los datos de la respuesta
    """
    instance = get_object_or_404(Post, pk=pk)
    if instance.publish > timezone.now() or instance.draft:
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = quote_plus(instance.title)

    initial_data = {
        'content_type': instance.get_content_type,
        'object_id': instance.id,
    }
    form = CommentForm(request.POST or None, initial=initial_data)
    if form.is_valid() and request.user.is_authenticated():
        c_type = form.cleaned_data.get('content_type')
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get('object_id')
        content_data = form.cleaned_data.get('content')
        parent_obj = None
        try:
            parent_id = request.POST.get('parent_id')
        except:
            parent_id = None

        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()

        new_comment, created = Comment.objects.get_or_create(
            user=request.user,
            content_type=content_type,
            object_id=obj_id,
            content=content_data,
            parent=parent_obj,
        )
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url());

    # List of similar posts
    post_qs_list = Post.objects.active()

    post_tags_ids = instance.tags.values_list('id', flat=True)
    similar_post = post_qs_list.filter(tags__in=post_tags_ids).exclude(id=instance.id)
    similar_post = similar_post.annotate(same_tags=Count('tags')).order_by('-same_tags')[:3]



    # commets in post
    comments = instance.comments #Comment.objects.filter_by_instance(instance)
    context = {
        'title': instance.title,
        'instance': instance,
        'share_string': share_string,
        'comments': comments,
        'comment_form': form,
        'similar_post': similar_post,
    }
    return render(request, 'posts/post_detail.html', context)


def post_list(request, tag_slug=None):
    """
    Gestiona la lista de articulos de blog publicados sin incluir los draft (borradores)
    :param tag_slug: filtrar pos por tags o categorias
    :param request: objeto HttpRequest con los datos de la petición
    :return: objeto HttpResponse con los datos de la respuesta.
    """
    today = timezone.now()

    post_qs_list = Post.objects.active() #.order_by('-timestamp')
    # Mira todo los post si incluidos los draft
    if request.user.is_staff or request.user.is_superuser:
        post_qs_list = Post.objects.all()
    search_query = request.GET.get('search')
    if search_query:
        post_qs_list = post_qs_list.filter(
            Q(title__icontains=search_query) |
            Q(content__icontains=search_query) |
            Q(user__first_name__icontains=search_query) |
            Q(user__last_name__icontains=search_query)
        ).distinct()
    #Filtrado de post por tags o categorias
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_qs_list = post_qs_list.filter(tags__name__in=[tag.name])

    paginator = Paginator(post_qs_list, 8)  # Show 25 contacts per page
    page_rqs_var = 'page'
    page = request.GET.get(page_rqs_var)
    try:
        post_qs = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        post_qs = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        post_qs = paginator.page(paginator.num_pages)
    context = {
        'object_list': post_qs,
        'title': 'List Post',
        'page_rqs_var': page_rqs_var,
        'today': today,
        'tags': tag,
    }
    return render(request, 'posts/list_posts.html', context)


def post_update(request, pk):
    """
    Gestiona la actualización de un articulo del blog
    :param request: objeto Httprequest con los datos de la petición
    :param pk: parametro que identifica un articulo del blog
    :return: objeto HttpResponse con los datos de la respuesta
    """
    if not request.user.is_authenticated:
        raise Http404
    instance = get_object_or_404(Post, pk=pk)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, 'Post Save', extra_tags='update-post')
        return redirect('post:url_post_detail', pk=instance.pk)
    context = {
        'title': instance.title,
        'instance': instance,
        'form': form
    }
    return render(request, 'posts/post_form.html', context)


def post_delete(request, pk=None):
    """
    Gestiona el borrado de un articulo del blog.
    :param request: objeto HttpRequest con los datos de la petición
    :param pk: parametro que identifica el aticulo del blog
    :return: objeto HttpResponse con los datos de la respuesta
    """
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, pk=pk)
    instance.delete()
    messages.success(request, 'Post Successfully Deleted')
    return redirect('url_post_list')


class PostLikeRedirectView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        """
        Add like a un articulo del blog cuando el usuario esta autenticado.
        """
        pk = self.kwargs.get('pk')
        obj = get_object_or_404(Post, pk=pk)
        url_ = obj.get_absolute_url()
        user = self.request.user
        if user.is_authenticated():
            if user in obj.likes.all():
                obj.likes.remove(user)
            else:
                obj.likes.add(user)
        return url_

posts/templates/posts/latest_posts.html
<h3>Latets posts Welldone</h3>
{% for post in latest_posts %}
    <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% empty %}
    There are not latest post
{% endfor %}

posts/templates/posts/list_posts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="breadcrumb-flex">
    <ol class="breadcrumb breadcrumb-box">
        <li><a href="{% url 'post:url_post_list' %}">Home</a></li>
        <li><a href="{{ instance.get_absolute_url }}">{{ instance.title }}</a></li>
    </ol>
</div>
<div class="title-list">
    <h1>Read, write and share stories</h1>
</div>

<div id="main-list-posts" class="flex-container">
    {% for post in object_list %}
        <div class="post">
            <div class="image-fixed">
                {% if post.image %}
                <a href="{{post.get_absolute_url}}">
                    <img src="{{post.image.url}}" alt="blog-img">
                </a>
                {% else %}
                <a href="{{post.get_absolute_url}}">
                    <img src="{% static "images/adam.jpg" %}" alt="blog-img">
                </a>
                {%endif%}
            </div>
            <div>
                <h3 id="title" class="html-text ">
                        <a href="{{post.get_absolute_url}}">{{post.title|truncatewords:13 }}</a>
                </h3>
                <div class="paragraph-text">{{ post.content|truncatewords:10 }}</div>
            </div>
            <div>
            {% if post.tags.count > 0 %}
                {% for tag in post.tags.all|slice:":2" %}
                <div class="category-tag">
                    <p class="category">
                        <span>
                            <i class="fa fa-tag" aria-hidden="true"></i><a href="{% url 'post:url_post_list_by_tag' tag.slug %}"> {{tag.name | truncatewords:2 }}</a>
                        </span>
                    </p>
                </div>
                {% endfor %}
                {% else %}
                <p class="category">No tag</p>
                {% endif %}
            </div>
            <div class="metadata">
                {% if post.user.profile.photo %}
                <div class="avatar">
                        <img src="{{ post.user.profile.photo.url }}" alt="">
                </div>
                {% else %}
                <div class="avatar">
                        <img src="{% static "images/adam.jpg" %}" alt="">
                </div>
                {% endif %}
                <div class="author">
                    {% if instance.user.get_full_name %}
                        <h4>Author: {{ post.user.get_full_name}}</h4>
                    {% else %}
                        <p> Author:@{{ post.user }}</p>
                    {% endif %}
                {% if post.publish > today %} Staff only: Post Pendiente{% endif %}
                    <span class="date">
                        <time class="timeago" datetime="{{post.publish}}">{{ post.publish | timesince }}</time>
                    </span>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
<div class="pagination">
    {% include 'posts/paginationstags.html'  %}
</div>
{% endblock %}
</div>

posts/templates/posts/list_tags.html
{#<h3>List Tags:</h3>#}
{% for tag in latest_tags %}
    <li class="navbar-item">
          <a href="{% url 'post:url_post_list_by_tag'  tag.slug %}">{{ tag.name }}</a>
    </li>
    {% empty %}
    There are not latest tags
{% endfor %}

posts/templates/posts/paginationstags.html
<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_rqs_var }}={{ object_list.previous_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_rqs_var }}={{ object_list.next_page_number }}
                 {% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">next
            </a>
        {% endif %}
    </span>
</div>

posts/templates/posts/post_detail.html
{% extends 'base-detail.html' %}
{% load blog_tags %}
{% load static %}

{% block content %}
<div class="breadcrumb-flex fix-detail">
    <ol class="breadcrumb breadcrumb-box">
        <li><a href="{% url 'post:url_post_list' %}">Home</a></li>
        <li><a href="{{ instance.get_absolute_url }}">{{ instance.title | truncatewords:6 }}</a></li>
    </ol>
</div>

    <div id="container-detail-post" data-idpost="{{instance.id}}">
        <div class="flex-container-header">
            <div class="metadata flex-item-1">
                {% if instance.user.profile.photo %}
                <div class="avatar">
                        <img src="{{ instance.user.profile.photo.url }}" alt="">
                </div>
                {% else %}
                <div class="avatar">
                        <img src="{% static "images/adam.jpg" %}"" alt="">
                </div>
                {% endif %}
                <div class="author">
                    {% if instance.user.get_full_name %}
                        <h4>Author: {{ instance.user.get_full_name}}</h4>
                    {% else %}
                        <p> Author:@{{ instance.user }}</p>
                    {% endif %}
                    {% if instance.publish > today %} Staff only: Post Pendiente{% endif %}

                        <span class="date-detail">
                            <time class="timeago" datetime="{{instance.publish}}">{{ instance.publish | timesince }}</time><br>
                            {% if instance.read_time >= 9 %}
                              Read time {{ instance.read_time | time:'i' | cut:'0'}} minutes
                            {% else %}
                              Read time {{ instance.read_time | time:'i'}} minutes
                            {% endif %}
                        </span>
                </div>
            </div>
        </div>
        <div class="html-text-detail">
              <h1 id="title">
                  {{instance.title|truncatewords:13 }}
            </h1>
          </div>

          <div class="post-detail-item">
            {% if instance.image %}
              <img src="{{ instance.image.url }}"  class="img-responsive" alt="">
            {% else %}
            <div class="avatar">
                    <img src="{% static "images/adam.jpg" %}"" alt="">
            </div>
            {% endif %}
          </div>
            <div class="detail-paragraph">
                <p>
                  <a data-href ="{{ instance.get_api_like_url }}"
                    data-like="{{ instance.likes.count }}"
                    class="like-btn" href="{{ instance.get_like_url }}">
                    <span class="count-likes">
                  {% if instance.likes.count %}
                    <i class="fa fa-heart" aria-hidden="true"></i>
                  {% else %}
                    <i class="fa fa-heart-o" aria-hidden="true"></i>
                  {% endif %}
                    {{ instance.likes.count }}</span>
                  </a>
                </p>
            </div>
            <!--<small class="flex-container-reverse">-->
              <!--{% if instance.draft %} <span class=" alert alert-danger">Draft</span>{% endif %}-->
              <!--{{ instance.publish | timesince }} ago |-->
              <!--{% if instance.read_time >= 9 %}-->
                  <!--Read time {{ instance.read_time | time:'i' | cut:'0'}} minutes-->
              <!--{% else %}-->
                  <!--Read time {{ instance.read_time | time:'i'}} minutes-->
              <!--{% endif %}-->
            <!--</small>-->
            <div class="container">
              <div class="row">
                <div class="col-xs-12">
	            <div class="detail-paragraph">
        	        <div class="lead markdown-air" id="content-markdown">{{ instance.content }}</div>
                    </div>
	        </div>
	      </div>
            </div>
                {% comment %}
                <p>
                    <div class="fb-like" data-href="{{ request.built_absolute_uri }}" data-layout="button_count" data-action="recommend" data-size="small" data-show-faces="false" data-share="true"></div>
                </p>

                {% endcomment %}
            </div>
    </div>
    <div class="similar-posts">
        {% include 'posts/similar_post.html' %}
    </div>
        {% include 'comments/comment_section.html' %}
{% endblock content %}

posts/templates/posts/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-sm-8 col-sm-offset-2">
    {{ form.media }}
        <h2> {{ title }}</h2><br/>
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy }}
            <input type="submit" class="btn btn-default" value="Create post">
        </form>

</div>
{% endblock content %}

posts/templates/posts/similar_post.html
{% load static %}
{% block content %}

<h3>Similar posts</h3>
<div class="category-similar-post-tag">
    <p class="category-similar-tag">
    {% if instance.tags.count > 0 %}
        <i class="fa fa-tags" aria-hidden="true"></i>
        {% for tag in instance.tags.all%}
        <span>
          <a href="{% url 'post:url_post_list_by_tag'  tag.slug %}">{{ tag.name }}</a>
        </span>
          {% if not  forloop.last %}, {% endif %}
        {% endfor %}
    {% endif %}
    </p>
</div>
<div class="flex-container">
    {% for post in similar_post %}
    <div class="post">
        <div class="image-fixed">
            {% if post.image %}
            <a href="{{post.get_absolute_url}}">
                <img src="{{post.image.url}}" alt="blog-img">
            </a>
            {% else %}
            <a href="{{post.get_absolute_url}}">
                <img src="{% static "images/adam.jpg" %}" alt="blog-img">
            </a>
            {%endif%}
        </div>
        <div>
            <h3 id="title-detail" class="html-text">
                    <a href="{{post.get_absolute_url}}">{{post.title|truncatewords:13 }}</a>
            </h3>
            <div class="paragraph-text">{{ post.get_markdown|truncatewords:15 }}</div>
        </div>
        {% if post.tags.count > 0 %}
            {% for tag in post.tags.all|slice:":2"%}
            <div class="category-tag">
                <p class="category">
                    <span>
                        <a href="{% url 'post:url_post_list_by_tag' tag.slug %}">{{tag.name | truncatewords:2}}</a>
                    </span>
                </p>
            </div>
        {% endfor %}
        {% else %}
        <p class="category">No tag</p>
        {% endif %}
        <div class="metadata">
            {% if post.user.profile.photo %}
            <div class="avatar">
                    <img src="{{ post.user.profile.photo.url }}" alt="">
            </div>
            {% else %}
            <div class="avatar">
                    <img src="{% static "images/adam.jpg" %}"" alt="">
            </div>
            {% endif %}
            <div class="author">
                {% if instance.user.get_full_name %}
                    <h4>Author: {{ post.user.get_full_name}}</h4>
                {% else %}
                    <p> Author:@{{ post.user }}</p>
                {% endif %}
            {% if post.publish > today %} Staff only: Post Pendiente{% endif %}
                <span class="date">
                    <time class="timeago" datetime="{{post.publish}}">{{ post.publish | timesince }}</time>
                </span>
            </div>

        </div>
    </div>
    {% empty %}
        <div class="no-similar-posts">
            <span>There are no similar posts. Find other posts with the tags you desire!</span>
        </div>
    {% endfor %}

    </div>
{% endblock %}